;;; disk-recovery-tests.el --- Targeted disk cleanup safety tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

;; Load the skill once with `mentat-skill-read' before running these tests.

(ert-deftest mentat-disk-test-runtime-retains-installed-binaries ()
  (let* ((root (make-temp-file "mentat-disk-test-" t))
         (target (expand-file-name "target" root))
         (release (expand-file-name "release" target))
         (fast-dev (expand-file-name "fast-dev" target))
         (binary (expand-file-name "neomacs" release))
         (dev-binary (expand-file-name "neomacs" fast-dev))
         (app (expand-file-name "Neomacs.app" root))
         (dev-app (expand-file-name "Neomacs Dev.app" root))
         (debug (expand-file-name "debug" target))
         (release-deps (expand-file-name "deps" release))
         (dev-deps (expand-file-name "deps" fast-dev)))
    (unwind-protect
        (progn
          (dolist (dir (list release fast-dev debug release-deps dev-deps))
            (make-directory dir t))
          (dolist (file (list binary dev-binary))
            (with-temp-file file (insert "binary"))
            (set-file-modes file #o755))
          (make-symbolic-link binary app)
          (make-symbolic-link dev-binary dev-app)
          (let* ((steps (mentat-disk--runtime-steps target app dev-app))
                 (removed (apply #'append (mapcar (lambda (step) (nth 2 step)) steps))))
            (should (member debug removed))
            (should (member release-deps removed))
            (should (member dev-deps removed))
            (dolist (path (list target release fast-dev binary dev-binary))
              (should-not (member path removed)))
            (delete-file app)
            (make-symbolic-link dev-binary app)
            (should-error (mentat-disk--runtime-steps target app dev-app)
                          :type 'user-error)
            (delete-file app)
            (make-symbolic-link binary app)
            (delete-file binary)
            (with-temp-file (expand-file-name "neomacs" release-deps)
              (insert "backing binary"))
            (make-symbolic-link (expand-file-name "neomacs" release-deps) binary)
            (should-error (mentat-disk--runtime-steps target app dev-app)
                          :type 'user-error)
            (delete-file binary)
            (with-temp-file binary (insert "binary"))
            (set-file-modes binary #o755)
            (delete-file dev-binary)
            (with-temp-file (expand-file-name "neomacs" dev-deps)
              (insert "backing binary"))
            (make-symbolic-link (expand-file-name "neomacs" dev-deps) dev-binary)
            (should-error (mentat-disk--runtime-steps target app dev-app)
                          :type 'user-error)))
      (delete-directory root t))))

(ert-deftest mentat-disk-test-diagnostics-exclude-active-traces ()
  (let* ((directory (make-temp-file "mentat-disk-diagnostics-" t))
         (mentat-diagnostic-capture-directory directory)
         (active (expand-file-name "mentat-diagnostic-v1-old.jsonl" directory)))
    (unwind-protect
        (cl-letf (((symbol-function 'mentat-disk--active-diagnostics)
                   (lambda () (list active))))
          (let* ((steps (mentat-disk--recovery-steps '("mentat-diagnostics") nil))
                 (args (nth 2 (car steps))))
            (should (equal (car (mentat-disk--locations)) directory))
            (should (equal (car args) directory))
            (should (equal (last args) '("-delete")))
            (should (member "+2880" args))
            (should (equal (member "!" args) (list "!" "-path" active "-delete")))))
      (delete-directory directory t))))

(ert-deftest mentat-disk-test-prune-output-is-suppressed ()
  (dolist (step (mentat-disk--recovery-steps
                 '("minikube-images" "minikube-cache") nil))
    (should (equal (nth 1 step) "sh"))
    (should (equal (car (nth 2 step)) "-c"))
    (should (string-match-p "docker exec minikube docker" (cadr (nth 2 step))))
    (should (string-suffix-p ">/dev/null" (cadr (nth 2 step))))
    (should-not (string-match-p "volume prune" (cadr (nth 2 step))))))

(ert-deftest mentat-disk-test-prune-stops-after-failure ()
  (let (commands results failure)
    (cl-letf (((symbol-function 'mentat-process-start)
               (lambda (_program args resolve _reject &rest _options)
                 (push args commands)
                 (funcall resolve (list :status 'exit :exit-code 1 :stderr "failed"))
                 #'ignore)))
      (mentat-disk--series
       '(("images" "docker" ("exec" "minikube" "docker" "image" "prune") 5)
         ("cache" "docker" ("exec" "minikube" "docker" "builder" "prune") 5))
       (lambda (entries stopped) (setq results entries failure stopped))
       #'ignore t)
      (should (equal failure "images"))
      (should (= (length commands) 1))
      (should (= (length results) 1)))))

(ert-deftest mentat-disk-test-recovery-refuses-prune-without-docker ()
  (let (outcome commands)
    (cl-letf (((symbol-function 'mentat-disk--inspect)
               (lambda (finish set-cancel)
                 (funcall set-cancel #'ignore)
                 (funcall finish
                          '(:available-kib 1024
                            :checks (("docker-info" :status exit :exit-code 1))))))
              ((symbol-function 'mentat-disk--series)
               (lambda (&rest steps) (setq commands steps))))
      (funcall (mentat-disk-recover '("minikube-cache"))
               (lambda (value) (setq outcome (list :resolved value)))
               (lambda (reason) (setq outcome (list :rejected reason)))
               #'ignore)
      (should (eq (car outcome) :rejected))
      (should (string-match-p "Docker is unavailable" (cadr outcome)))
      (should-not commands))))

(provide 'disk-recovery-tests)
;;; disk-recovery-tests.el ends here
