;;; elasticsearch-tests.el --- Elastic MCP lifecycle tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'mentat-elisp-library)

(load (expand-file-name "elasticsearch.el"
                        (file-name-directory (or load-file-name buffer-file-name)))
      nil t t)

(ert-deftest mentat-elastic-mcp-preserves-registered-empty-objects ()
  (dolist (input '("[\"test\",{}]" "[\"test\",{\"query\":{}}]"))
    (let ((args (mentat--elisp-json-arguments
                 input "{}" '(tool arguments)))
          sent)
      (cl-letf (((symbol-function 'url-retrieve)
                 (lambda (&rest _) (setq sent url-request-data) nil)))
        (mentat-elastic-mcp--request "test-key" (car args) (cadr args)
                                     #'ignore #'ignore))
      (let* ((payload (json-parse-string (decode-coding-string sent 'utf-8)
                                         :null-object :null))
             (actual (gethash "arguments" (gethash "params" payload))))
        (should (hash-table-p actual))
        (when (cadr args)
          (should (hash-table-p (gethash "query" actual))))))))

(ert-deftest mentat-elastic-mcp-preserves-credential-rejections ()
  (dolist (category '(mentat-tool-authentication mentat-tool-cancelled))
    (let ((reason (list category "Credential failure"))
          failures reject-credential cleaned)
      (cl-letf (((symbol-function 'mentat-auth-source-secret-async)
                 (lambda (_label _hosts _success reject &rest _options)
                   (setq reject-credential reject)
                   (funcall reject reason)
                   (lambda () (setq cleaned t))))
                ((symbol-function 'mentat-elastic-mcp--request)
                 (lambda (&rest _) (ert-fail "Unexpected HTTP request"))))
        (funcall (mentat-elastic-mcp--starter "test" nil)
                 #'ignore (lambda (value) (push value failures)) #'ignore)
        (funcall reject-credential reason)
        (should (= (length failures) 1))
        (should (eq (car failures) reason))
        (should cleaned)))))

(ert-deftest mentat-elastic-mcp-serializes-registered-array-arguments ()
  (let* ((arguments-json "[\"test\",{\"indices\":[\"logs-*\"],\"nested\":[{\"label\":\"שלום\"}],\"enabled\":false}]")
         (args (mentat--elisp-json-arguments
                arguments-json "{}" '(tool arguments)))
         sent)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (&rest _)
                 (setq sent url-request-data) nil)))
      (mentat-elastic-mcp--request "test-key" (car args) (cadr args)
                                   #'ignore #'ignore))
    (should-not (multibyte-string-p sent))
    (let* ((payload (json-parse-string (decode-coding-string sent 'utf-8)
                                      :object-type 'alist :array-type 'list
                                      :false-object :false))
           (actual (alist-get 'arguments (alist-get 'params payload))))
      (should (equal actual (cadr args))))))
(ert-deftest mentat-elastic-mcp-cancel-ignores-late-result ()
  (let (complete cancel results)
    (cl-letf (((symbol-function 'mentat-auth-source-secret-async)
               (lambda (_label _hosts success _reject &rest _options)
                 (funcall success "test-key") #'ignore))
              ((symbol-function 'mentat-elastic-mcp--request)
               (lambda (_key _tool _args success _reject)
                 (setq complete success) nil)))
      (funcall (mentat-elastic-mcp--starter "test" nil)
               (lambda (value) (push value results)) #'ignore
               (lambda (cleanup) (setq cancel cleanup)))
      (funcall cancel)
      (funcall complete 'late)
      (should-not results))))

(ert-deftest mentat-elastic-mcp-startup-error-rejects ()
  (let (failure)
    (cl-letf (((symbol-function 'mentat-auth-source-secret-async)
               (lambda (_label _hosts success _reject &rest _options)
                 (funcall success "test-key") #'ignore))
              ((symbol-function 'mentat-elastic-mcp--request)
               (lambda (&rest _) (error "Connection setup failed"))))
      (funcall (mentat-elastic-mcp--starter "test" nil)
               #'ignore (lambda (message) (setq failure message)) #'ignore)
      (should (string-match-p "Connection setup failed" failure)))))

(ert-deftest mentat-elastic-mcp-timeout-settles-once ()
  (let (expire complete cancel failures results)
    (cl-letf (((symbol-function 'mentat-auth-source-secret-async)
               (lambda (_label _hosts success _reject &rest _options)
                 (funcall success "test-key") #'ignore))
              ((symbol-function 'mentat-elastic-mcp--request)
               (lambda (_key _tool _args success _reject)
                 (setq complete success) nil))
              ((symbol-function 'run-at-time)
               (lambda (_seconds _repeat callback &rest args)
                 (setq expire (lambda () (apply callback args))) 'test-timer))
              ((symbol-function 'cancel-timer) #'ignore))
      (funcall (mentat-elastic-mcp--starter "test" nil)
               (lambda (value) (push value results))
               (lambda (message) (push message failures))
               (lambda (cleanup) (setq cancel cleanup)))
      (should expire)
      (funcall expire)
      (funcall complete 'late)
      (funcall cancel)
      (should (= (length failures) 1))
      (should (string-match-p "test.*timed out" (car failures)))
      (should-not results))))
