;;; session-manager-tests.el --- Session send regression tests -*- lexical-binding: t; -*-

;;; Commentary:
;; Exercise session handoff callbacks without launching Pi or sending prompts.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'mentat)

(load (expand-file-name "session-manager.el"
                        (file-name-directory (or load-file-name buffer-file-name)))
      nil t t)

(ert-deftest mentat-session-send-waits-for-acknowledgment ()
  (dolist (live '(t nil))
    (ert-info ((format "Initially live: %S" live))
      (with-temp-buffer
        (let* ((entry (mentat--registry-entry-create :session-id "session-id"))
               (view (mentat--buffer-make :buffer (current-buffer) :status "idle"))
               (submissions 0)
               (resolutions 0)
               result failure cleanup ready accepted)
          (cl-letf (((symbol-function 'mentat--open-live-view)
                     (lambda (_id) (and live view)))
                    ((symbol-function 'mentat--open-entry-view)
                     (lambda (_entry on-ready _on-error)
                       (setq ready on-ready)))
                    ((symbol-function 'mentat--buffer-submit)
                     (lambda (_view _prompt _attachments on-accepted _on-error)
                       (cl-incf submissions)
                       (setq accepted on-accepted)
                       "request-id")))
            (funcall (mentat-session-manager--send-starter entry "test prompt")
                     (lambda (value)
                       (cl-incf resolutions)
                       (setq result value))
                     (lambda (reason) (setq failure reason))
                     (lambda (callback) (setq cleanup callback)))
            (should-not failure)
            (should-not result)
            (should (functionp cleanup))
            (unless live
              (should (= submissions 0))
              (should (functionp ready))
              (funcall ready view nil))
            (should (= submissions 1))
            (should (functionp accepted))
            (should-not result)
            (funcall accepted nil '((id . "request-id")))
            (should-not failure)
            (should (equal (alist-get 'session-id result) "session-id"))
            (should (equal (alist-get 'request-id result) "request-id"))
            (should (equal (alist-get 'resumed result) (not live)))
            (funcall accepted nil '((id . "request-id")))
            (should (= resolutions 1))
            (funcall cleanup)
            (should (buffer-live-p (current-buffer)))))))))

(ert-deftest mentat-session-send-rejects-startup-errors ()
  (dolist (stage '(lookup resume))
    (ert-info ((format "Failure stage: %S" stage))
      (let ((entry (mentat--registry-entry-create :session-id "session-id"))
            result failures cleanup)
        (cl-letf (((symbol-function 'mentat--open-live-view)
                   (lambda (_id)
                     (when (eq stage 'lookup)
                       (error "Mock startup failure"))
                     nil))
                  ((symbol-function 'mentat--open-entry-view)
                   (lambda (&rest _args)
                     (error "Mock startup failure"))))
          (funcall (mentat-session-manager--send-starter entry "test prompt")
                   (lambda (value) (setq result value))
                   (lambda (reason) (push reason failures))
                   (lambda (callback) (setq cleanup callback)))
          (should-not result)
          (should (equal failures '("Mock startup failure")))
          (should (functionp cleanup))
          (funcall cleanup)
          (should (equal failures '("Mock startup failure"))))))))

(provide 'session-manager-tests)
;;; session-manager-tests.el ends here
