(deftheme bobs-badger
  "Created 2019-05-02.")

(custom-theme-set-variables
 'bobs-badger
 '(ansi-color-names-vector ["black" "#E2434C" "#86B187" "#E0D063" "#84C452" "#E18CBB" "#8AC6F2" "white"]))

(custom-theme-set-faces
 'bobs-badger
 '(button ((t (:underline t))))
 '(link ((t (:bold t :foreground "#8AC6F2" :underline t :weight bold))))
 '(cursor ((t (:background "#F28B86"))))
 '(escape-glyph ((t (:foreground "#F28B86" :bold t))))
 '(fringe ((t (:foreground "#F6F3E8" :background "black"))))
 '(highlight ((t (:background "#403f37"))))
 '(lazy-highlight ((t (:background "#E0D063" :foreground "black" :weight extra-bold))))
 '(isearch ((t (:background "cyan" :foreground "black" :weight extra-bold))))
 '(success ((t (:foreground "#8ACDAA" :weight bold))))
 '(warning ((t (:foreground "#E18CBB" :weight bold))))
 '(region ((t (:background "#3c5260"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#656868" :background "black")) (t :inverse-video nil)))
 '(mode-line-inactive ((t (:background "#2F2F2F" :foreground "black" :box nil))))
 '(mode-line-buffer-id ((t (:foreground "#F28B86"))))
 '(minibuffer-prompt ((t (:foreground "#BF93C3"))))
 '(linum ((t (:foreground "#656868" :background "black"))))
 '(font-lock-warning-face ((t (:foreground "#E0D063" :weight bold))))
 '(font-lock-function-name-face ((t (:foreground "#EA9847"))))
 '(font-lock-variable-name-face ((t (:foreground "#F28B86"))))
 '(font-lock-keyword-face ((t (:foreground "#8AC6F2"))))
 '(font-lock-comment-face ((t (:foreground "#656868"))))
 '(font-lock-type-face ((t (:foreground "#C7B299"))))
 '(font-lock-constant-face ((t (:foreground "#635770"))))
 '(font-lock-builtin-face ((t (:foreground "#BF93C3"))))
 '(font-lock-preprocessor-face ((t (:foreground "#C7B299"))))
 '(font-lock-string-face ((t (:foreground "#86B187"))))
 '(org-document-info-keyword ((t (:foreground "#9AA68E"))))
 '(org-document-title ((t (:foreground "#F28B86" :height 1.5))))
 '(org-archived ((t (:foreground "#F6F3E8" :weight bold))))
 '(org-checkbox ((t (:foreground "#FBF9F3" :foreground "#9AA68E" :box (:line-width 1 :style released-button)))))
 '(org-done ((t (:foreground "#84C452" :strike-through t))))
 '(org-todo ((t (:foreground "#E2434C"))))
 '(org-formula ((t (:foreground "#BF93C3"))))
 '(org-headline-done ((t (:strike-through t :foreground "#656868"))))
 '(org-hide ((t (:foreground "#171717"))))
 '(org-level-1 ((t (:foreground "#8AC6F2"))))
 '(org-level-2 ((t (:foreground "#BF93C3"))))
 '(org-level-3 ((t (:foreground "#EA9847"))))
 '(org-level-4 ((t (:foreground "#E0D063"))))
 '(org-level-5 ((t (:foreground "#c4c1ad"))))
 '(org-level-6 ((t (:foreground "#86B187"))))
 '(org-level-7 ((t (:foreground "#AC8952"))))
 '(org-level-8 ((t (:foreground "#65A399"))))
 '(org-link ((t (:foreground "#8ACDAA" :underline t))))
 '(org-agenda-date ((t (:foreground "#8AC6F2"))))
 '(org-date ((t (:foreground "#8ACDAA" :underline t))))
 '(org-agenda-date-today ((t (:foreground "#F28B86" :weight light :slant italic))))
 '(org-agenda-structure ((t (:inherit font-lock-comment-face))))
 '(org-special-keyword ((t (:foreground "#9AA68E" :weight normal))))
 '(org-table ((t (:foreground "#9AA68E"))))
 '(org-tag ((t (:bold t :foreground "#EA9847" :strike-through nil))))
 '(org-warning ((t (:bold t :foreground "#E18CBB" :weight bold))))
 '(org-column ((t (:background "black"))))
 '(org-column-title ((t (:background "black" :foreground "#84C452" :underline t))))
 '(org-mode-line-clock ((t (:foreground "#E0D063"))))
 '(org-footnote ((t (:foreground "#8ACDAA" :underline t))))
 '(org-code ((t (:foreground "#9AA68E"))))
 '(org-verbatim ((t (:inherit org-code))))
 '(comint-highlight-prompt ((t (:inherit eshell-prompt))))
 '(tree-sitter-hl-face:method.call ((t (:inherit (font-lock-function-name-face) :underline nil))))
 '(tree-sitter-hl-face:property ((t (:inherit (font-lock-property-name-face) :underline nil))))
 '(tree-sitter-hl-face:number ((t (:foreground "#00008B8B0000" :background "#171717"))))
 '(default ((t (:foreground "#F6F3E8" :background "#1c1616")))))

(provide-theme 'bobs-badger)
