;;; modus-kanagawa.el --- Kanagawa palettes on Modus Themes -*- lexical-binding: t; -*-

;;; Commentary:
;; Canonical Kanagawa Wave, Dragon, and Lotus palettes adapted to the
;; Modus Themes semantic palette and face infrastructure.
;; Sources:
;; https://github.com/rebelot/kanagawa.nvim/blob/master/lua/kanagawa/colors.lua
;; https://github.com/rebelot/kanagawa.nvim/blob/master/lua/kanagawa/themes.lua

;;; Code:

(require 'modus-themes)

(defgroup modus-kanagawa nil
  "Kanagawa palettes on the Modus Themes infrastructure."
  :group 'faces
  :group 'modus-themes
  :prefix "modus-kanagawa-")

(defconst modus-kanagawa-light-themes '(modus-kanagawa-lotus)
  "Light themes in the Modus Kanagawa family.")

(defconst modus-kanagawa-dark-themes
  '(modus-kanagawa-wave modus-kanagawa-dragon)
  "Dark themes in the Modus Kanagawa family.")

(defconst modus-kanagawa-items
  (append modus-kanagawa-light-themes modus-kanagawa-dark-themes)
  "All themes in the Modus Kanagawa family.")

(defconst modus-kanagawa-common-palette-mappings
  '((keyword kanagawa-keyword)
    (builtin kanagawa-special-2)
    (constant kanagawa-constant)
    (string kanagawa-string)
    (docstring kanagawa-string)
    (docmarkup kanagawa-special-1)
    (comment kanagawa-comment)
    (fnname kanagawa-function)
    (type kanagawa-type)
    (variable fg-main)
    (preprocessor kanagawa-preprocessor)
    (property kanagawa-identifier)
    (rx-backslash kanagawa-operator)
    (rx-construct kanagawa-special-1)
    (number kanagawa-number)
    (punctuation kanagawa-punctuation)
    (operator kanagawa-operator)
    (fg-link kanagawa-function)
    (underline-link kanagawa-function)
    (fg-link-symbolic kanagawa-type)
    (underline-link-symbolic kanagawa-type)
    (fg-link-visited kanagawa-keyword)
    (underline-link-visited kanagawa-keyword)
    (fg-prose-code kanagawa-type)
    (bg-prose-code unspecified)
    (fg-prose-macro kanagawa-special-2)
    (fg-prose-verbatim kanagawa-string)
    (bg-prose-verbatim unspecified)
    (prose-done green)
    (prose-todo kanagawa-error)
    (prose-tag kanagawa-keyword)
    (prose-metadata kanagawa-comment)
    (prose-metadata-value fg-dim)
    (fg-heading-0 kanagawa-type)
    (fg-heading-1 kanagawa-identifier)
    (fg-heading-2 kanagawa-function)
    (fg-heading-3 kanagawa-keyword)
    (fg-heading-4 kanagawa-special-1)
    (fg-heading-5 kanagawa-string)
    (fg-heading-6 kanagawa-preprocessor)
    (fg-heading-7 kanagawa-type)
    (fg-heading-8 kanagawa-comment)
    (accent-0 kanagawa-function)
    (accent-1 kanagawa-identifier)
    (accent-2 kanagawa-type)
    (accent-3 kanagawa-preprocessor)
    (fg-completion-match-0 kanagawa-function)
    (fg-completion-match-1 kanagawa-identifier)
    (fg-completion-match-2 kanagawa-type)
    (fg-completion-match-3 kanagawa-preprocessor)
    (fg-prompt kanagawa-function)
    (err kanagawa-error)
    (warning kanagawa-warning)
    (info kanagawa-info)
    (underline-err kanagawa-error)
    (underline-warning kanagawa-warning)
    (underline-note kanagawa-hint)
    (keybind kanagawa-function)
    (name kanagawa-keyword)
    (identifier kanagawa-identifier))
  "Semantic mappings shared by all Modus Kanagawa variants.")

(defconst modus-kanagawa-wave-palette
  (modus-themes-generate-palette
   '((bg-main "#1F1F28")
     (bg-dim "#181820")
     (bg-alt "#1a1a22")
     (bg-active "#363646")
     (bg-inactive "#1a1a22")
     (border "#2A2A37")
     (fringe "#1F1F28")
     (fg-main "#DCD7BA")
     (fg-dim "#C8C093")
     (fg-alt "#727169")
     (red "#C34043")
     (red-warmer "#E46876")
     (red-cooler "#E82424")
     (red-intense "#FF5D62")
     (green "#98BB6C")
     (green-faint "#76946A")
     (yellow "#C0A36E")
     (yellow-warmer "#FFA066")
     (yellow-intense "#E6C384")
     (blue "#7E9CD8")
     (blue-warmer "#957FB8")
     (blue-cooler "#7FB4CA")
     (blue-intense "#A3D4D5")
     (magenta "#957FB8")
     (magenta-warmer "#D27E99")
     (magenta-cooler "#938AA9")
     (cyan "#7AA89F")
     (cyan-warmer "#6A9589")
     (cyan-cooler "#7FB4CA")
     (rust "#E46876")
     (gold "#E6C384")
     (olive "#98BB6C")
     (slate "#7E9CD8")
     (indigo "#957FB8")
     (maroon "#C34043")
     (pink "#D27E99")
     (bg-added "#2B3328")
     (bg-added-faint "#181820")
     (bg-added-refine "#2B3328")
     (bg-added-fringe "#76946A")
     (fg-added "#76946A")
     (fg-added-intense "#98BB6C")
     (bg-removed "#43242B")
     (bg-removed-faint "#181820")
     (bg-removed-refine "#43242B")
     (bg-removed-fringe "#C34043")
     (fg-removed "#C34043")
     (fg-removed-intense "#E46876")
     (bg-changed "#252535")
     (bg-changed-faint "#181820")
     (bg-changed-refine "#49443C")
     (bg-changed-fringe "#DCA561")
     (fg-changed "#DCA561")
     (fg-changed-intense "#E6C384")
     (bg-diff-context "#181820")
     (bg-region "#223249")
     (fg-region "#DCD7BA")
     (bg-hl-line "#363646")
     (bg-completion "#223249")
     (bg-hover "#181820")
     (bg-hover-secondary "#1a1a22")
     (bg-search-current "#2D4F67")
     (bg-search-lazy "#223249")
     (bg-search-replace "#43242B")
     (bg-mode-line-active "#16161D")
     (fg-mode-line-active "#DCD7BA")
     (border-mode-line-active "#54546D")
     (bg-mode-line-inactive "#181820")
     (fg-mode-line-inactive "#727169")
     (border-mode-line-inactive "#2A2A37")
     (fg-line-number-inactive "#54546D")
     (fg-line-number-active "#C8C093")
     (bg-line-number-inactive "#2A2A37")
     (bg-line-number-active "#2A2A37")
     (bg-prose-block-delimiter "#16161D")
     (fg-prose-block-delimiter "#727169")
     (bg-prose-block-contents "#16161D")
     (cursor "#DCD7BA")
     (kanagawa-level-0 "#16161D")
     (kanagawa-level-1 "#181820")
     (kanagawa-level-2 "#2A2A37")
     (kanagawa-level-3 "#54546D")
     (kanagawa-level-4 "#727169")
     (kanagawa-level-5 "#C8C093")
     (kanagawa-level-6 "#DCD7BA")
     (kanagawa-user-bg "#2A2A37")
     (kanagawa-bold "#FFA066")
     (kanagawa-block-bg "#16161D")
     (kanagawa-string "#98BB6C")
     (kanagawa-number "#D27E99")
     (kanagawa-constant "#FFA066")
     (kanagawa-identifier "#E6C384")
     (kanagawa-parameter "#b8b4d0")
     (kanagawa-function "#7E9CD8")
     (kanagawa-keyword "#957FB8")
     (kanagawa-operator "#C0A36E")
     (kanagawa-preprocessor "#E46876")
     (kanagawa-type "#7AA89F")
     (kanagawa-comment "#727169")
     (kanagawa-punctuation "#9CABCA")
     (kanagawa-special-1 "#7FB4CA")
     (kanagawa-special-2 "#E46876")
     (kanagawa-special-3 "#FF5D62")
     (kanagawa-error "#E82424")
     (kanagawa-warning "#FF9E3B")
     (kanagawa-info "#658594")
     (kanagawa-hint "#6A9589"))
   'cool modus-themes-vivendi-palette
   modus-kanagawa-common-palette-mappings)
  "Complete canonical palette for Modus Kanagawa Wave.")

(defconst modus-kanagawa-dragon-palette
  (modus-themes-generate-palette
   '((bg-main "#181616")
     (bg-dim "#12120f")
     (bg-alt "#1D1C19")
     (bg-active "#393836")
     (bg-inactive "#1D1C19")
     (border "#282727")
     (fringe "#181616")
     (fg-main "#c5c9c5")
     (fg-dim "#C8C093")
     (fg-alt "#737c73")
     (red "#c4746e")
     (red-warmer "#b98d7b")
     (red-cooler "#E82424")
     (red-intense "#E46876")
     (green "#87a987")
     (green-faint "#8a9a7b")
     (yellow "#c4b28a")
     (yellow-warmer "#b6927b")
     (yellow-intense "#E6C384")
     (blue "#8ba4b0")
     (blue-warmer "#8992a7")
     (blue-cooler "#949fb5")
     (blue-intense "#7FB4CA")
     (magenta "#a292a3")
     (magenta-warmer "#b6927b")
     (magenta-cooler "#8992a7")
     (cyan "#8ea4a2")
     (cyan-warmer "#87a987")
     (cyan-cooler "#8ba4b0")
     (rust "#c4746e")
     (gold "#c4b28a")
     (olive "#8a9a7b")
     (slate "#8ba4b0")
     (indigo "#8992a7")
     (maroon "#c4746e")
     (pink "#a292a3")
     (bg-added "#2B3328")
     (bg-added-faint "#12120f")
     (bg-added-refine "#2B3328")
     (bg-added-fringe "#76946A")
     (fg-added "#76946A")
     (fg-added-intense "#98BB6C")
     (bg-removed "#43242B")
     (bg-removed-faint "#12120f")
     (bg-removed-refine "#43242B")
     (bg-removed-fringe "#C34043")
     (fg-removed "#C34043")
     (fg-removed-intense "#E46876")
     (bg-changed "#252535")
     (bg-changed-faint "#12120f")
     (bg-changed-refine "#49443C")
     (bg-changed-fringe "#DCA561")
     (fg-changed "#DCA561")
     (fg-changed-intense "#E6C384")
     (bg-diff-context "#12120f")
     (bg-region "#223249")
     (fg-region "#c5c9c5")
     (bg-hl-line "#393836")
     (bg-completion "#223249")
     (bg-hover "#12120f")
     (bg-hover-secondary "#1D1C19")
     (bg-search-current "#2D4F67")
     (bg-search-lazy "#223249")
     (bg-search-replace "#43242B")
     (bg-mode-line-active "#0d0c0c")
     (fg-mode-line-active "#c5c9c5")
     (border-mode-line-active "#625e5a")
     (bg-mode-line-inactive "#12120f")
     (fg-mode-line-inactive "#737c73")
     (border-mode-line-inactive "#282727")
     (fg-line-number-inactive "#625e5a")
     (fg-line-number-active "#C8C093")
     (bg-line-number-inactive "#282727")
     (bg-line-number-active "#282727")
     (bg-prose-block-delimiter "#0d0c0c")
     (fg-prose-block-delimiter "#737c73")
     (bg-prose-block-contents "#0d0c0c")
     (cursor "#c5c9c5")
     (kanagawa-level-0 "#0d0c0c")
     (kanagawa-level-1 "#12120f")
     (kanagawa-level-2 "#282727")
     (kanagawa-level-3 "#625e5a")
     (kanagawa-level-4 "#737c73")
     (kanagawa-level-5 "#C8C093")
     (kanagawa-level-6 "#c5c9c5")
     (kanagawa-user-bg "#282727")
     (kanagawa-bold "#FFA066")
     (kanagawa-block-bg "#0d0c0c")
     (kanagawa-string "#8a9a7b")
     (kanagawa-number "#a292a3")
     (kanagawa-constant "#b6927b")
     (kanagawa-identifier "#c4b28a")
     (kanagawa-parameter "#a6a69c")
     (kanagawa-function "#8ba4b0")
     (kanagawa-keyword "#8992a7")
     (kanagawa-operator "#c4746e")
     (kanagawa-preprocessor "#c4746e")
     (kanagawa-type "#8ea4a2")
     (kanagawa-comment "#737c73")
     (kanagawa-punctuation "#9e9b93")
     (kanagawa-special-1 "#949fb5")
     (kanagawa-special-2 "#c4746e")
     (kanagawa-special-3 "#c4746e")
     (kanagawa-error "#E82424")
     (kanagawa-warning "#FF9E3B")
     (kanagawa-info "#658594")
     (kanagawa-hint "#6A9589"))
   'warm modus-themes-vivendi-palette
   modus-kanagawa-common-palette-mappings)
  "Complete canonical palette for Modus Kanagawa Dragon.")

(defconst modus-kanagawa-lotus-palette
  (modus-themes-generate-palette
   '((bg-main "#f2ecbc")
     (bg-dim "#dcd5ac")
     (bg-alt "#e5ddb0")
     (bg-active "#e4d794")
     (bg-inactive "#e7dba0")
     (border "#e7dba0")
     (fringe "#f2ecbc")
     (fg-main "#545464")
     (fg-dim "#43436c")
     (fg-alt "#8a8980")
     (red "#c84053")
     (red-warmer "#cc6d00")
     (red-cooler "#d7474b")
     (red-intense "#e82424")
     (green "#6f894e")
     (green-faint "#6e915f")
     (yellow "#77713f")
     (yellow-warmer "#cc6d00")
     (yellow-intense "#de9800")
     (blue "#4d699b")
     (blue-warmer "#624c83")
     (blue-cooler "#4e8ca2")
     (blue-intense "#5d57a3")
     (magenta "#b35b79")
     (magenta-warmer "#c84053")
     (magenta-cooler "#766b90")
     (cyan "#597b75")
     (cyan-warmer "#6f894e")
     (cyan-cooler "#4e8ca2")
     (rust "#cc6d00")
     (gold "#77713f")
     (olive "#6f894e")
     (slate "#4d699b")
     (indigo "#624c83")
     (maroon "#c84053")
     (pink "#b35b79")
     (bg-added "#b7d0ae")
     (bg-added-faint "#e5ddb0")
     (bg-added-refine "#b7d0ae")
     (bg-added-fringe "#6e915f")
     (fg-added "#6e915f")
     (fg-added-intense "#6f894e")
     (bg-removed "#d9a594")
     (bg-removed-faint "#e5ddb0")
     (bg-removed-refine "#d9a594")
     (bg-removed-fringe "#d7474b")
     (fg-removed "#d7474b")
     (fg-removed-intense "#c84053")
     (bg-changed "#d7e3d8")
     (bg-changed-faint "#e5ddb0")
     (bg-changed-refine "#f9d791")
     (bg-changed-fringe "#de9800")
     (fg-changed "#de9800")
     (fg-changed-intense "#836f4a")
     (bg-diff-context "#dcd5ac")
     (bg-region "#c9cbd1")
     (fg-region "#545464")
     (bg-hl-line "#e4d794")
     (bg-completion "#c7d7e0")
     (bg-hover "#dcd5ac")
     (bg-hover-secondary "#e5ddb0")
     (bg-search-current "#b5cbd2")
     (bg-search-lazy "#c7d7e0")
     (bg-search-replace "#d9a594")
     (bg-mode-line-active "#d5cea3")
     (fg-mode-line-active "#545464")
     (border-mode-line-active "#716e61")
     (bg-mode-line-inactive "#dcd5ac")
     (fg-mode-line-inactive "#8a8980")
     (border-mode-line-inactive "#e7dba0")
     (fg-line-number-inactive "#a09cac")
     (fg-line-number-active "#43436c")
     (bg-line-number-inactive "#e7dba0")
     (bg-line-number-active "#e7dba0")
     (bg-prose-block-delimiter "#d5cea3")
     (fg-prose-block-delimiter "#8a8980")
     (bg-prose-block-contents "#d5cea3")
     (cursor "#545464")
     (kanagawa-level-0 "#d5cea3")
     (kanagawa-level-1 "#dcd5ac")
     (kanagawa-level-2 "#e7dba0")
     (kanagawa-level-3 "#a09cac")
     (kanagawa-level-4 "#8a8980")
     (kanagawa-level-5 "#545464")
     (kanagawa-level-6 "#43436c")
     (kanagawa-user-bg "#c9cbd1")
     (kanagawa-bold "#cc6d00")
     (kanagawa-block-bg "#d5cea3")
     (kanagawa-string "#6f894e")
     (kanagawa-number "#b35b79")
     (kanagawa-constant "#cc6d00")
     (kanagawa-identifier "#77713f")
     (kanagawa-parameter "#5d57a3")
     (kanagawa-function "#4d699b")
     (kanagawa-keyword "#624c83")
     (kanagawa-operator "#836f4a")
     (kanagawa-preprocessor "#c84053")
     (kanagawa-type "#597b75")
     (kanagawa-comment "#8a8980")
     (kanagawa-punctuation "#4e8ca2")
     (kanagawa-special-1 "#6693bf")
     (kanagawa-special-2 "#c84053")
     (kanagawa-special-3 "#c84053")
     (kanagawa-error "#e82424")
     (kanagawa-warning "#e98a00")
     (kanagawa-info "#5a7785")
     (kanagawa-hint "#5e857a"))
   'warm modus-themes-operandi-palette
   modus-kanagawa-common-palette-mappings)
  "Complete canonical palette for Modus Kanagawa Lotus.")

(dolist (spec '((modus-kanagawa-wave-palette-overrides "Wave")
                (modus-kanagawa-dragon-palette-overrides "Dragon")
                (modus-kanagawa-lotus-palette-overrides "Lotus")))
  (eval `(defcustom ,(car spec) nil
           ,(format "Palette overrides for Modus Kanagawa %s." (cadr spec))
           :group 'modus-kanagawa
           :type '(repeat (list symbol (choice symbol string))))))

(defconst modus-kanagawa-custom-faces
  '(
    ;; Kanagawa typography and canonical syntax emphasis.
    `(bold ((,c :foreground ,kanagawa-bold :weight bold)))
    `(bold-italic ((,c :foreground ,kanagawa-bold :weight bold :slant italic)))
    `(italic ((,c :foreground ,kanagawa-keyword :slant italic)))
    `(font-lock-comment-face ((,c :foreground ,kanagawa-comment :slant italic)))
    `(font-lock-comment-delimiter-face ((,c :foreground ,kanagawa-comment :slant italic)))
    `(font-lock-function-name-face ((,c :foreground ,kanagawa-function :weight normal)))
    `(font-lock-keyword-face ((,c :foreground ,kanagawa-keyword :weight bold :slant italic)))
    `(font-lock-variable-name-face ((,c :foreground ,fg-main)))
    `(highlight ((,c :foreground ,fg-main :background ,bg-dim)))
    `(shadow ((,c :foreground ,kanagawa-level-3)))

    ;; Window chrome.
    `(separator-line
      ((default :extend t)
       (((type tty)) :foreground ,border :strike-through t)
       (t :height 0.1 :background ,border :foreground ,border)))
    `(fringe ((,c :background ,bg-main :foreground ,kanagawa-level-3)))
    `(margin ((,c :background ,bg-main)))
    `(line-number ((,c :background ,bg-line-number-inactive :foreground ,fg-line-number-inactive)))
    `(line-number-current-line ((,c :background ,bg-line-number-active :foreground ,fg-line-number-active)))
    `(header-line ((,c :background ,bg-dim :foreground ,fg-main :box nil)))
    `(header-line-inactive ((,c :background ,bg-main :foreground ,kanagawa-level-3 :box nil)))
    `(mode-line ((,c :background ,bg-mode-line-active :foreground ,fg-mode-line-active :box nil)))
    `(mode-line-active ((,c :background ,bg-mode-line-active :foreground ,fg-mode-line-active :box nil)))
    `(mode-line-inactive ((,c :background ,bg-mode-line-inactive :foreground ,fg-mode-line-inactive :box nil)))
    `(vertical-border ((,c :background ,bg-main :foreground ,border)))
    `(window-divider ((,c :background ,border :foreground ,border)))
    `(window-divider-first-pixel ((,c :background ,border :foreground ,border)))
    `(window-divider-last-pixel ((,c :background ,border :foreground ,border)))

    ;; Markdown and markdown-ts-mode.
    `(markdown-header-face ((,c :foreground ,kanagawa-identifier :weight normal)))
    `(markdown-header-face-1 ((,c :inherit markdown-header-face :foreground ,kanagawa-identifier)))
    `(markdown-header-face-2 ((,c :inherit markdown-header-face :foreground ,kanagawa-function)))
    `(markdown-header-face-3 ((,c :inherit markdown-header-face :foreground ,kanagawa-keyword)))
    `(markdown-header-face-4 ((,c :inherit markdown-header-face :foreground ,kanagawa-type)))
    `(markdown-header-face-5 ((,c :inherit markdown-header-face :foreground ,kanagawa-special-1)))
    `(markdown-header-face-6 ((,c :inherit markdown-header-face :foreground ,kanagawa-comment)))
    `(markdown-bold-face ((,c :inherit bold)))
    `(markdown-italic-face ((,c :inherit italic)))
    `(markdown-code-face ((,c :inherit fixed-pitch :background ,kanagawa-block-bg)))
    `(markdown-inline-code-face ((,c :inherit fixed-pitch :foreground ,kanagawa-type :background unspecified)))
    `(markdown-pre-face ((,c :inherit markdown-code-face :extend t)))
    `(markdown-blockquote-face ((,c :foreground ,kanagawa-comment :slant italic)))
    `(markdown-markup-face ((,c :foreground ,kanagawa-level-3)))
    `(markdown-list-face ((,c :foreground ,kanagawa-punctuation)))
    `(markdown-link-face ((,c :foreground ,kanagawa-function :underline t)))
    `(markdown-table-face ((,c :inherit fixed-pitch)))
    `(markdown-ts-bold ((,c :inherit bold)))
    `(markdown-ts-emphasis ((,c :inherit markdown-italic-face)))
    `(markdown-ts-heading-1 ((,c :inherit markdown-header-face-1)))
    `(markdown-ts-heading-2 ((,c :inherit markdown-header-face-2)))
    `(markdown-ts-heading-3 ((,c :inherit markdown-header-face-3)))
    `(markdown-ts-heading-4 ((,c :inherit markdown-header-face-4)))
    `(markdown-ts-heading-5 ((,c :inherit markdown-header-face-5)))
    `(markdown-ts-heading-6 ((,c :inherit markdown-header-face-6)))
    `(markdown-ts-code-span ((,c :inherit markdown-inline-code-face :background unspecified)))
    `(markdown-ts-code-block ((,c :inherit markdown-pre-face :extend t)))
    `(markdown-ts-indented-code-block ((,c :inherit markdown-ts-code-block)))
    `(markdown-ts-code-block-markup-hidden ((,c :background ,kanagawa-block-bg :extend t)))
    `(markdown-ts-block-quote ((,c :inherit markdown-blockquote-face)))
    `(markdown-ts-delimiter ((,c :inherit markdown-markup-face)))
    `(markdown-ts-list-marker ((,c :inherit markdown-list-face)))
    `(markdown-ts-link ((,c :inherit markdown-link-face)))
    `(markdown-ts-link-destination ((,c :foreground ,kanagawa-function :underline t)))
    `(markdown-ts-table ((,c :inherit markdown-table-face :extend t)))
    `(markdown-ts-table-header ((,c :inherit markdown-ts-table :foreground ,kanagawa-identifier :weight semi-bold)))
    `(markdown-ts-table-delimiter-cell ((,c :foreground ,kanagawa-level-3)))
    `(markdown-ts-task-checked ((,c :foreground ,green :weight semi-bold)))
    `(markdown-ts-task-unchecked ((,c :foreground ,kanagawa-comment)))

    ;; VUI primitives used by Mentat.
    `(vui-field-placeholder ((,c :foreground ,kanagawa-comment :slant italic)))
    `(vui-table-header ((,c :background ,kanagawa-level-1 :foreground ,fg-main :weight semi-bold)))
    `(vui-table-border ((,c :foreground ,kanagawa-level-3)))

    ;; Mentat transcript surfaces and semantic states.
    `(mentat-muted-face ((,c :foreground ,kanagawa-comment)))
    `(mentat-user-message-face ((,c :background ,kanagawa-user-bg :foreground ,fg-main :extend t)))
    `(mentat--user-message-surface-face ((,c :background ,kanagawa-user-bg :foreground ,fg-main :extend t)))
    `(mentat-user-marker-face ((,c :foreground ,kanagawa-function :weight bold)))
    `(mentat-assistant-marker-face ((,c :foreground ,green :weight bold)))
    `(mentat-control-face ((,c :inherit fixed-pitch :foreground ,kanagawa-type)))
    `(mentat-queue-face ((,c :foreground ,kanagawa-comment :slant italic)))
    `(mentat-thinking-summary-face ((,c :foreground ,kanagawa-type :weight semi-bold)))
    `(mentat-thinking-content-face ((,c :foreground ,kanagawa-comment)))
    `(mentat-thinking-aborted-face ((,c :foreground ,kanagawa-error :weight semi-bold)))
    `(mentat-extension-progress-face ((,c :foreground ,kanagawa-warning :weight semi-bold)))
    `(mentat-custom-message-label-face ((,c :foreground ,kanagawa-keyword :weight bold)))
    `(mentat-custom-message-face ((,c :foreground ,kanagawa-comment)))
    `(mentat-behavior-reminder-face ((,c :foreground ,kanagawa-comment :slant italic)))
    `(mentat-tool-running-face ((,c :foreground ,kanagawa-warning :weight semi-bold)))
    `(mentat-tool-success-face ((,c :foreground ,green :weight semi-bold)))
    `(mentat-tool-error-face ((,c :foreground ,kanagawa-error :weight semi-bold)))
    `(mentat-tool-cancelled-face ((,c :foreground ,kanagawa-comment :weight semi-bold)))
    `(mentat-tool-header-face ((,c :foreground ,fg-main :weight semi-bold)))
    `(mentat-tool-name-face ((,c :foreground ,kanagawa-keyword :weight bold :slant italic)))
    `(mentat-tool-argument-face ((,c :foreground ,kanagawa-comment)))
    `(mentat-tool-output-face ((,c :foreground ,fg-dim)))
    `(mentat-tool-line-number-face ((,c :foreground ,kanagawa-comment)))
    `(mentat-tool-disclosure-face ((,c :foreground ,kanagawa-comment :slant italic :height 0.9)))
    `(mentat-run-prompt-face ((,c :foreground ,kanagawa-function :weight bold)))
    `(mentat-run-output-face ((,c :background ,kanagawa-block-bg :foreground ,fg-main :extend t)))
    `(mentat-run-output-border-face ((,c :background ,kanagawa-level-1 :foreground ,kanagawa-comment :weight semi-bold :extend t)))
    `(mentat-code-block-face ((,c :background ,kanagawa-block-bg :extend t)))
    `(mentat-code-block-border-face ((,c :foreground ,kanagawa-comment :weight semi-bold)))
    `(mentat--code-block-opening-face ((,c :background ,kanagawa-level-1 :foreground ,kanagawa-comment :weight semi-bold :extend t)))
    `(mentat-table-border-face ((,c :foreground ,kanagawa-level-3)))
    `(mentat-table-header-face ((,c :background ,kanagawa-level-1 :foreground ,fg-main :weight semi-bold :extend t)))
    `(mentat-table-alternate-row-face ((,c :background ,kanagawa-level-1 :extend t)))
    `(mentat-compaction-face ((,c :foreground ,magenta :weight semi-bold)))
    `(mentat-compaction-error-face ((,c :foreground ,kanagawa-error :weight semi-bold)))
    `(mentat-cache-drop-face ((,c :foreground ,magenta :weight semi-bold)))
    `(mentat-notification-info-face ((,c :foreground ,kanagawa-info :weight semi-bold)))
    `(mentat-notification-warning-face ((,c :foreground ,kanagawa-warning :weight semi-bold)))
    `(mentat-notification-error-face ((,c :foreground ,kanagawa-error :weight semi-bold)))
    `(mentat-mode-line-idle-face ((,c :foreground ,green :weight bold)))
    `(mentat-mode-line-active-face ((,c :foreground ,kanagawa-warning :weight bold)))
    `(mentat-mode-line-error-face ((,c :foreground ,kanagawa-error :weight bold)))
    `(mentat-mode-line-metadata-face ((,c :foreground ,kanagawa-comment)))
    `(mentat-mode-line-model-face ((,c :foreground ,fg-main :weight semi-bold)))
    `(mentat-mode-line-profile-face ((,c :foreground ,kanagawa-type :weight bold)))
    `(mentat-mode-line-context-warning-face ((,c :foreground ,kanagawa-warning)))
    `(mentat-mode-line-context-error-face ((,c :foreground ,kanagawa-error)))
    `(mentat-reference-face ((,c :foreground ,kanagawa-function :weight semi-bold)))
    `(mentat-image-caption-face ((,c :foreground ,kanagawa-comment :weight semi-bold)))
    `(mentat-open-working-face ((,c :foreground ,kanagawa-warning :weight bold)))
    `(mentat-open-ready-face ((,c :foreground ,green)))
    `(mentat-open-attention-face ((,c :foreground ,kanagawa-warning :weight bold)))
    `(mentat-open-closed-face ((,c :foreground ,kanagawa-comment)))
    `(mentat-skill-face ((,c :foreground ,magenta :weight semi-bold)))
    `(mentat-subagent-name-face ((,c :foreground ,kanagawa-type :weight semi-bold)))
    `(mentat-subagent-foreground-face ((,c :foreground ,kanagawa-function :weight semi-bold)))
    `(mentat-subagent-background-face ((,c :foreground ,kanagawa-keyword :weight semi-bold)))
    `(mentat-subagent-queued-face ((,c :foreground ,kanagawa-comment :weight semi-bold)))
    `(mentat-history-current-face ((,c :foreground ,kanagawa-function :weight bold)))
    `(mentat-rpc-log-incoming-face ((,c :foreground ,green :weight bold)))
    `(mentat-rpc-log-outgoing-face ((,c :foreground ,kanagawa-function :weight bold)))
    `(mentat-prompt-inspector-source-kind ((,c :foreground ,kanagawa-keyword :weight semi-bold)))
    `(mentat-prompt-inspector-source-label ((,c :foreground ,fg-dim :weight semi-bold)))
    `(mentat-show-me-title-face ((,c :foreground ,kanagawa-identifier :weight bold :height 1.2)))
    `(mentat-show-me-note-info-face ((,c :foreground ,kanagawa-info)))
    `(mentat-show-me-note-success-face ((,c :foreground ,green)))
    `(mentat-show-me-note-warning-face ((,c :foreground ,kanagawa-warning))))
  "Shared faces for all Modus Kanagawa variants.")

(provide 'modus-kanagawa)
;;; modus-kanagawa.el ends here
