(deftheme naysayer
  "The naysayer color theme")

(custom-theme-set-variables
 'naysayer
 '(linum-format " %5i "))

(custom-theme-set-faces
 'naysayer
 '(region ((t (:foreground nil :background "#0000ff"))))
 '(cursor ((t (:background "#ffffff"))))
 '(fringe ((t (:background "#062329" :foreground "#ffffff"))))
 '(linum ((t (:background "#062329" :foreground "#ffffff"))))
 '(highlight ((t (:foreground nil :background "#0000ff"))))
 '(font-lock-keyword-face ((t (:foreground "#ffffff"))))
 '(font-lock-type-face ((t (:foreground "#8cde94"))))
 '(font-lock-constant-face ((t (:foreground "#7ad0c6"))))
 '(font-lock-variable-name-face ((t (:foreground "#c1d1e3"))))
 '(font-lock-builtin-face ((t (:foreground "#ffffff"))))
 '(font-lock-string-face ((t (:foreground "#2ec09c"))))
 '(font-lock-comment-face ((t (:foreground "#44b340"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#44b340"))))
 '(font-lock-doc-face ((t (:foreground "#44b340"))))
 '(font-lock-function-name-face ((t (:foreground "#ffffff"))))
 '(font-lock-doc-string-face ((t (:foreground "#2ec09c"))))
 '(font-lock-preprocessor-face ((t (:foreground "#8cde94"))))
 '(font-lock-warning-face ((t (:foreground "#ffaa00"))))
 '(trailing-whitespace ((t (:foreground nil :background "#ffaa00"))))
 '(whitespace-trailing ((t (:background nil :foreground "#ffaa00" :inverse-video t))))
 '(linum ((t (:foreground "#126367" :background "#062329"))))
 '(linum-relative-current-face ((t (:foreground "#ffffff" :background "#062329"))))
 '(line-number ((t (:foreground "#126367" :background "#062329"))))
 '(line-number-current-line ((t (:foreground "#ffffff" :background "#062329"))))
 '(hl-line ((t (:background "#0b3335"))))
 '(hl-line-face ((t (:background "#0b3335"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#AE81FF"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#66D9EF"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#A6E22E"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#E6DB74"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#FD971F"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#F92672"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#AE81FF"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#66D9EF"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#A6E22E"))))
 '(rainbow-delimiters-depth-10-face ((t (:foreground "#E6DB74"))))
 '(rainbow-delimiters-depth-11-face ((t (:foreground "#FD971F"))))
 '(rainbow-delimiters-depth-12-face ((t (:foreground "#F92672"))))
 '(mode-line-buffer-id ((t (:foreground "#062329" :distant-foreground "#d1b897" :text "#d1b897" :weight bold))))
 '(mode-line ((t (:inverse-video unspecified :underline unspecified :foreground "#062329" :background "#d1b897" :box nil))))
 '(powerline-active1 ((t (:background "#d1b897" :foreground "#062329"))))
 '(powerline-active2 ((t (:background "#d1b897" :foreground "#062329"))))
 '(mode-line-inactive ((t (:inverse-video unspecified :underline unspecified :foreground "#d1b897" :background "#062329" :box nil))))
 '(powerline-inactive1 ((t (:background "#062329" :foreground "#d1b897"))))
 '(powerline-inactive2 ((t (:background "#062329" :foreground "#d1b897"))))
 '(js2-function-call ((t (:inherit (font-lock-function-name-face)))))
 '(js2-function-param ((t (:foreground "#d1b897"))))
 '(js2-jsdoc-tag ((t (:foreground "#ffffff"))))
 '(js2-jsdoc-type ((t (:foreground "#7ad0c6"))))
 '(js2-jsdoc-value ((t (:foreground "#d1b897"))))
 '(js2-object-property ((t (:foreground "#d1b897"))))
 '(js2-external-variable ((t (:foreground "#7ad0c6"))))
 '(js2-error ((t (:foreground "#ff0000"))))
 '(js2-warning ((t (:foreground "#ffaa00"))))
 '(highlight-numbers-number ((t (:foreground "#7ad0c6"))))
 '(default ((t (:foreground "#d1b897" :background "#062329" :weight normal)))))

(provide-theme 'naysayer)
